=== arosdami/EFEW32WebXML/EFEW32_0402/XDMEFEW32.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="vendeglatas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="efew32_Vendeglatas">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="etterem">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nev" type="xs:string" />
                                        <xs:element name="csillag" type="xs:string" />
                                        <xs:element name="cim">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="varos" type="xs:string" />
                                                    <xs:element name="utca" type="xs:string" />
                                                    <xs:element name="hazszam" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="foszakacs">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nev" type="xs:string" />
                                                    <xs:element name="eletkor" type="xs:string" />
                                                    <xs:element name="vegzettseg"
                                                        maxOccurs="unbounded" type="xs:string" />
                                                </xs:sequence>
                                                <xs:attribute name="fkod" use="required" />
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="szakacs" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nev" type="xs:string" />
                                                    <xs:element name="reszleg" type="xs:string" />
                                                    <xs:element name="vegzettseg" type="xs:string" />
                                                </xs:sequence>
                                                <xs:attribute name="szkod" use="required" />
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="gyakornok">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nev" type="xs:string" />
                                                    <xs:element name="gyakorlat">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="kezdete"
                                                                    type="xs:string" />
                                                                <xs:element name="idotartama"
                                                                    type="xs:string" />
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="muszak" maxOccurs="unbounded"
                                                        type="xs:string" />
                                                </xs:sequence>
                                                <xs:attribute name="gykod" use="required" />
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="ekod" use="required" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="vendeg">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nev" type="xs:string" />
                                        <xs:element name="eletkor" type="xs:string" />
                                        <xs:element name="cim">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="varos" type="xs:string" />
                                                    <xs:element name="utca" type="xs:string" />
                                                    <xs:element name="hazszam" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="vkod" use="required" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="rendeles">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="etterem_ref" type="xs:string" />
                                        <xs:element name="vendeg_ref" type="xs:string" />
                                        <xs:element name="osszeg" type="xs:string" />
                                        <xs:element name="etel" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== arosdami/EFEW32WebXML/EFEW32_0402/XMLEFEW32.xml
<?xml version="1.0" encoding="UTF-8"?>
<vendeglatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XDMEFEW32.xsd">
    <efew32_Vendeglatas>
        <etterem ekod="E_01">
            <nev>Pataki Ízek Étterem</nev>
            <csillag>4</csillag>
            <cim>
                <varos>Sárospatak</varos>
                <utca>Rákóczi út</utca>
                <hazszam>12</hazszam>
            </cim>

            <foszakacs fkod="F_101">
                <nev>Kovács István</nev>
                <eletkor>52</eletkor>
                <vegzettseg>Mesterlevél</vegzettseg>
                <vegzettseg>Szakács szakoktató</vegzettseg>
            </foszakacs>

            <szakacs szkod="SZ_201">
                <nev>Nagy Lajos</nev>
                <reszleg>Hidegkonyha</reszleg>
                <vegzettseg>Szakács technikus</vegzettseg>
            </szakacs>
            <szakacs szkod="SZ_202">
                <nev>Tóth Gábor</nev>
                <reszleg>Grill részleg</reszleg>
                <vegzettseg>Cukrász-Szakács</vegzettseg>
            </szakacs>

            <gyakornok gykod="GY_301">
                <nev>Varga Bence</nev>
                <gyakorlat>
                    <kezdete>2026-02-01</kezdete>
                    <idotartama>3 hónap</idotartama>
                </gyakorlat>
                <muszak>Délelőtt</muszak>
                <muszak>Hétvége</muszak>
            </gyakornok>
        </etterem>

        <vendeg vkod="V_501">
            <nev>Minta Adél</nev>
            <eletkor>28</eletkor>
            <cim>
                <varos>Szerencs</varos>
                <utca>Petőfi tér</utca>
                <hazszam>5</hazszam>
            </cim>
        </vendeg>

        <rendeles>
            <etterem_ref>E_01</etterem_ref>
            <vendeg_ref>V_501</vendeg_ref>
            <osszeg>12500</osszeg>
            <etel>Szarvaspörkölt dödöllével</etel>
        </rendeles>
    </efew32_Vendeglatas>
</vendeglatas>
